import { spawn } from 'node:child_process';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';

export function normalizeGraphvizSvg(svg: string): string {
    return svg.replace(/<!-- Generated by graphviz version .*? -->/gi, '<!-- Generated by Graphviz -->');
}

export async function renderDotWithGraphviz(
    dot: string,
    outputPath: string,
    options: { executable?: string } = {}
): Promise<void> {
    const executable = options.executable ?? 'dot';
    const svg = await new Promise<string>((resolve, reject) => {
        const child = spawn(executable, ['-Tsvg'], { stdio: ['pipe', 'pipe', 'pipe'] });
        const stdout: Buffer[] = [];
        const stderr: Buffer[] = [];
        child.stdout.on('data', (chunk: Buffer) => stdout.push(chunk));
        child.stderr.on('data', (chunk: Buffer) => stderr.push(chunk));
        child.on('error', error => {
            if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
                reject(new Error(`Graphviz executable "${executable}" was not found. Install Graphviz and ensure "dot" is available on PATH.`));
            } else {
                reject(new Error(`Unable to start Graphviz: ${error.message}`));
            }
        });
        child.on('close', code => {
            if (code === 0) resolve(Buffer.concat(stdout).toString('utf8'));
            else reject(new Error(`Graphviz exited with code ${code}: ${Buffer.concat(stderr).toString('utf8').trim()}`));
        });
        child.stdin.end(dot);
    });
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, normalizeGraphvizSvg(svg));
}
